/* eslint-disable @typescript-eslint/naming-convention */
/* eslint-disable camelcase */
/* eslint-disable no-undefined */
import * as services from '@/services'
import { useTranslation } from 'react-i18next'

export default () => {
  const [t] = useTranslation()

  const {
    addProject,
    updateProject,
    deleteProject,
    openProject,
    stopProject,
    updateMember,
    deleteMember,
    addMember,
    getProjectPermission,
    addPermission,
    deletePermission,
    updatePermission,
    getPermission,
    setPermission,
    getProjectMember,
    addStoryConfigField,
    deleteStoryConfigField,
    updateStoryConfigField,
    addStoryConfigCategory,
    updateStoryConfigCategory,
    deleteStoryConfigCategory,
    changeCategoryStatus,
    changeStoryConfigCategory,
    addStoryConfigWorkflow,
    updateStoryConfigWorkflow,
    deleteStoryConfigWorkflow,
    sortchangeWorkflow,
    saveWorkflowStatus,
    getWorkflowInfo,
    saveWorkflowConfig,
    addStoryConfigStatus,
    deleteStoryConfigStatus,
    updateStoryConfigStatus,
    getGroupList,
    addProjectGroup,
    updateProjectGroup,
    deleteProjectGroup,
  } = services.project

  return {
    addProject,
    updateProject,
    deleteProject,
    openProject,
    stopProject,
    updateMember,
    deleteMember,
    addMember,
    getProjectPermission,
    addPermission,
    deletePermission,
    updatePermission,
    getPermission,
    setPermission,
    getProjectMember,
    addStoryConfigField,
    deleteStoryConfigField,
    updateStoryConfigField,
    addStoryConfigCategory,
    updateStoryConfigCategory,
    deleteStoryConfigCategory,
    changeCategoryStatus,
    changeStoryConfigCategory,
    addStoryConfigWorkflow,
    updateStoryConfigWorkflow,
    deleteStoryConfigWorkflow,
    sortchangeWorkflow,
    saveWorkflowStatus,
    getWorkflowInfo,
    saveWorkflowConfig,
    addStoryConfigStatus,
    deleteStoryConfigStatus,
    updateStoryConfigStatus,
    getGroupList,
    addProjectGroup,
    updateProjectGroup,
    deleteProjectGroup,
  }
}
